spring.application.name=Notification-service
server.port=8081
# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=app_user
spring.datasource.password=app_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
kafka.ingest.topic=notification.ingest
kafka.audit.topic=notification.audit
# Kafka Broker configuration
spring.kafka.bootstrap-servers=localhost:9092
#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000