messaging:
  providers:
    kafka:
      enabled: true
    aws:
      enabled: true
  fallback:
    rabbitmq:
      enabled: true
    mqtt:
      enabled: true

  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: rajatpatil.dev@gmail.com
      password: mypassword

      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true